let suggestions = [
	'Youtube' ,
	'Dilatadores',
	'Diseñador Web',
	'Formularios con HTML y CSS',
	'Lenceria',
	'Bondage',
	'Programación en Python',
	'Mensaje',
	'Desarrollo Backend',
	'email',
	'contactanos',
	'Como crear un sitio web responsive',
	'quienes somos',
	'Aprender React desde cero',
	'Aprender Css desde cero',
	'Aprender Html desde cero',
	'Estimuladores',
	'Aprender python desde cero',
];